#!/usr/bin/env bash
# install-task-hooks.sh — write or merge <settings-dir>/.claude/settings.json
# with cmux-tab-agents Task() visibility hooks (PreToolUse, PostToolUse,
# SubagentStop). Install into the planner's working directory so the hooks
# fire when the planner runs Task() subagents.
#
# Usage:
#   install-task-hooks.sh <settings-dir>
#
# Mirrors the pattern of install-tab-hooks.sh. Idempotent: re-running with
# the same directory leaves the same content. Requires jq.

set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage: install-task-hooks.sh <settings-dir>

Generates or merges <settings-dir>/.claude/settings.json with
cmux-tab-agents Task() visibility hooks:
  PreToolUse   — spawns a cmux tab for each new Task() subagent
  PostToolUse  — appends tool results to the per-agent JSONL log
  SubagentStop — appends a FINISHED line when the subagent completes
EOF
  exit 1
}

[[ $# -eq 1 ]] || usage
WT="$1"
[[ -d "$WT" ]] || { echo "install-task-hooks: directory '$WT' does not exist" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOKS_DIR="$SKILL_ROOT/hooks"

for h in pre_tool_use.sh post_tool_use.sh subagent_stop.sh; do
  [[ -x "$HOOKS_DIR/$h" ]] \
    || { echo "install-task-hooks: hook missing or not executable: $HOOKS_DIR/$h" >&2; exit 1; }
done

command -v jq >/dev/null 2>&1 || { echo "install-task-hooks: jq is required" >&2; exit 1; }

DEST_DIR="$WT/.claude"
DEST="$DEST_DIR/settings.json"
mkdir -p "$DEST_DIR"

# Build the desired hooks block.
DESIRED=$(jq -cn \
  --arg ptu "$HOOKS_DIR/pre_tool_use.sh" \
  --arg pou "$HOOKS_DIR/post_tool_use.sh" \
  --arg ss  "$HOOKS_DIR/subagent_stop.sh" \
  '{
     PreToolUse:   [{ hooks: [{ type: "command", command: $ptu }] }],
     PostToolUse:  [{ hooks: [{ type: "command", command: $pou }] }],
     SubagentStop: [{ hooks: [{ type: "command", command: $ss  }] }]
   }')

# Read existing settings (if any), merge our hooks, write back.
EXISTING="{}"
if [[ -f "$DEST" ]]; then
  if ! EXISTING=$(jq '.' "$DEST" 2>/dev/null); then
    echo "install-task-hooks: existing $DEST is not valid JSON; refusing to overwrite" >&2
    exit 1
  fi
fi

MERGED=$(jq -n \
  --argjson existing "$EXISTING" \
  --argjson desired "$DESIRED" \
  '
    ($existing.hooks // {}) as $eh
    | $existing
    + { _comment: "Generated by cmux-tab-agents install-task-hooks.sh; do not edit manually.",
        hooks: ($eh + $desired) }
  ')

TMP=$(mktemp "$DEST.XXXXXX")
printf '%s\n' "$MERGED" > "$TMP"
mv "$TMP" "$DEST"
