#!/usr/bin/env bash
# install-tab-hooks.sh — write or merge `<worktree>/.claude/settings.json`
# so that SessionStart / PostToolUse / Stop hooks fire for the tab-agent's
# `claude` process.
#
# Usage:
#   install-tab-hooks.sh <worktree>
#
# The hook scripts referenced live alongside this script under ../hooks.
# Their absolute paths (resolved at install time) are inlined so that the
# generated settings.json is self-contained and survives plugin-cache
# relocations.
#
# Idempotency: re-running with the same worktree leaves the same content;
# any pre-existing settings.json is merged so unrelated keys / hooks are
# preserved. Requires `jq` and `python3` (already required by other scripts
# in this skill).

set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage: install-tab-hooks.sh <worktree>

Generates or merges <worktree>/.claude/settings.json with cmux-tab-agents
SessionStart / PostToolUse / Stop hooks pointing at this checkout's
hooks/ directory.
EOF
  exit 1
}

[[ $# -eq 1 ]] || usage
WT="$1"
[[ -d "$WT" ]] || { echo "install-tab-hooks: worktree '$WT' does not exist" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOKS_DIR="$SKILL_ROOT/hooks"

for h in session_start.sh post_tool_use.sh stop.sh; do
  [[ -x "$HOOKS_DIR/$h" ]] || { echo "install-tab-hooks: hook missing or not executable: $HOOKS_DIR/$h" >&2; exit 1; }
done

command -v jq >/dev/null 2>&1 || { echo "install-tab-hooks: jq is required" >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "install-tab-hooks: python3 is required" >&2; exit 1; }

DEST_DIR="$WT/.claude"
DEST="$DEST_DIR/settings.json"
mkdir -p "$DEST_DIR"

# Build the desired hooks block. The Claude Code hook config format expects
# an array of matchers per event, each with its own `hooks` array.
DESIRED=$(jq -cn \
  --arg ss "$HOOKS_DIR/session_start.sh" \
  --arg pt "$HOOKS_DIR/post_tool_use.sh" \
  --arg st "$HOOKS_DIR/stop.sh" \
  '{
     SessionStart: [{ hooks: [{ type: "command", command: $ss }] }],
     PostToolUse:  [{ hooks: [{ type: "command", command: $pt }] }],
     Stop:         [{ hooks: [{ type: "command", command: $st }] }]
   }')

# Read existing settings (if any), merge our hooks into the .hooks key, and
# write back. Existing non-cmux-tab-agents hooks under other event names are
# preserved untouched. Existing entries for our three events are overwritten
# (we own them).
EXISTING="{}"
if [[ -f "$DEST" ]]; then
  if ! EXISTING=$(jq '.' "$DEST" 2>/dev/null); then
    echo "install-tab-hooks: existing $DEST is not valid JSON; refusing to overwrite" >&2
    exit 1
  fi
fi

MERGED=$(jq -n \
  --argjson existing "$EXISTING" \
  --argjson desired "$DESIRED" \
  '
    ($existing.hooks // {}) as $eh
    | $existing
    + { _comment: "Generated by cmux-tab-agents install-tab-hooks.sh; do not edit manually.",
        hooks: ($eh + $desired) }
  ')

# Atomic write so an interrupted run never leaves a half-written file.
TMP=$(mktemp "$DEST.XXXXXX")
printf '%s\n' "$MERGED" > "$TMP"
mv "$TMP" "$DEST"
